### ISSUE TITLE
Suggestion: Discord or something

### ISSUE THREAD

**Issue by PacketSender642** [Spydr06/CSpydr#1]
so we can talk share ideas etc.

**Comment by Spydr06** [comment]
If more people are really interested in it, I think, I could arrange that. For now, the subreddit ([r/CSpydr](https://www.reddit.com/r/CSpydr/)) has to be enough, as I currently don't have the time to moderate and be active on multiple places. If you want to share your Ideas with me, you could also send a DM to me on Reddit ([u/mcspiderfe](https://www.reddit.com/user/MCSpiderFe/)
