### ISSUE TITLE
Incorrect library name when building - glfw

### ISSUE THREAD

**Issue by Its-Kenta** [Spydr06/CSpydr#11]
It seems that glfw binding is picking up incorrect lib name as it's trying to collect glfw while on arch its named glfw3.
![Screenshot from 2023-01-25 17-07-23](https://user-images.githubusercontent.com/106167071/214632354-6595f2e3-d462-4eab-a76a-56815c99b471.png)

**Comment by Spydr06** [comment]
I'll really have to implement `pkg-config`-support soon to avoid these errors

**Comment by Its-Kenta** [comment]
Pkg-config would seriously be helpful here. Linux is uh… A wild place when it comes to naming conventions for libs. Also not to mention actually, I realised I’ve build my glfw from source so that’s the name they’ve given to it.

**Comment by Its-Kenta** [comment]
Unfortunetly that didn't work and I believe it's because I'm trying to link it to a static lib. Does CSpydr only accept shared libs for now?

Passing static lib results in:
```
Compiling  main.csp
  Optimizing (2/2) evaluate constant expressions
  Generating assembly for x86_64-linux-gnu
  Linking    a.out (glfw3, GL)
ld: /home/kenta/.cache/cspydr/a.out.o: in function `.main':
/home/kenta/Documents/Playgrounds/main.csp:5: undefined reference to `glfwInit'
ld: /home/kenta/Documents/Playgrounds/main.csp:8: undefined reference to `glfwCreateWindow'
ld: /home/kenta/Documents/Playgrounds/main.csp:10: undefined reference to `glfwTerminate'
ld: /home/kenta/Documents/Playgrounds/main.csp:14: undefined reference to `glfwMakeContextCurrent'
ld: /home/kenta/Documents/Playgrounds/main.csp:16: undefined reference to `glfwWindowShouldClose'
ld: /home/kenta/Documents/Playgrounds/main.csp:24: undefined reference to `glfwSwapBuffers'
ld: /home/kenta/Documents/Playgrounds/main.csp:25: undefined reference to `glfwPollEvents'
ld: /home/kenta/Documents/Playgrounds/main.csp:28: undefined reference to `glfwTerminate'
error linking code. (exit code 1)
```

**Comment by Spydr06** [comment]
I've only ever tried it with shared libraries... So yea, static libs are something I'll have to sort out too

**Comment by Spydr06** [comment]
Fixed with the implementation of `pkgconf`
