### ISSUE TITLE
Error while loading shared libs

### ISSUE THREAD

**Issue by Its-Kenta** [Spydr06/CSpydr#14]
I wanted to mess about creating a CSpydr binding to Raylib which seems to work when using `[link("raylib")]` as recommended.
When building the executable it seems to work and linker finds the shared lib, however. When trying to run the binary we're met with error:

`./main: error while loading shared libraries: libraylib.so.450: cannot open shared object file: No such file or directory`
While the shared libs are also present in the same dir as the executable.

Am I missing something here?

**Comment by Its-Kenta** [comment]
My bad.
LD was unaware of the path where the libs are located at.

**Comment by Spydr06** [comment]
fyi, I just implemented pkg-config support, so errors like this should now be thrown at compile-time (or better: resolved)
