### ISSUE TITLE
Allow for alias naming when utilising extern "C" 

### ISSUE THREAD

**Issue by Its-Kenta** [Spydr06/CSpydr#15]
Apologies for a vague subject, unsure how to properly form it in words.
What I mean by this suggestion is to provide an ability to create CSpydr internal function names as an alias to what is being linked with a C library.

e.g.

```
extern "C" fn cFunctionNameA(): int32;
extern "C" fn cFunctionNameB(): int32;
```

The name matches exactly the same as it does in the C code, but it would be great to give the user an ability to also provide their own internal CSpydr name e.g.:

```
fn c_function_nameA() @extern "C" cFunctionNameA(): int32;
fn c_function_nameB() @extern "C" cFunctionNameB(): int32;
```

I'm most certain there would be some ways to make it look pretty, but it would be great if it was possible to do so.
Correct me if I'm wrong and this already exists?

**Comment by Spydr06** [comment]
how about this syntax:
```
[export("cFunctionNameA")]
extern "C" fn c_function_name_a();
```

**Comment by Its-Kenta** [comment]
Yeah! Looks great

**Comment by Spydr06** [comment]
`export` would have the advantage that you could specify other names for non-extern functions

**Comment by Its-Kenta** [comment]
Sounds good to me

**Comment by Spydr06** [comment]
Implemented in [2d38552](https://github.com/Spydr06/CSpydr/commit/2d38552b7e103347ca7ca74a9cbcc2fa5361ab9b)!

**Comment by Its-Kenta** [comment]
How is it supposed to be run? The same was as an example shown above?

**Comment by Spydr06** [comment]
as above:
```
[export("exportedName")]
extern "C" fn your_name();
```

**Comment by Its-Kenta** [comment]
I've just tested it, however this does not seem to work:

```
[export("GetScreenWidth")]
extern "C" fn get_screen_width(): i32;
```

Returns:
```
main.o: in function `.main':
main.csp:17: undefined reference to `export'
```

**Comment by Spydr06** [comment]
waiiit what??? xD

**Comment by Spydr06** [comment]
Fixed. As always, one-line bugs xD

**Comment by Its-Kenta** [comment]
Might be worth doing some unit tests in the future to catch those bugs

**Comment by Its-Kenta** [comment]
Tested and works fine now.

**Comment by Spydr06** [comment]
yea, there is a test system for the std library and the compiler, but the tests are missing...
