### ISSUE TITLE
Macros in namespaces & calling them with namespace

### ISSUE THREAD

**Issue by Its-Kenta** [Spydr06/CSpydr#17]
Is there any reason behind this? I think it might be conflicting if we have two different imports where the macros share the same name (low possibility, but still worth thinking over it.)

What would happen if library A & library B both have a macro named PI and not under a namespace? Which macro would be called?

Is there any possibility to allow adding macros in namespaces and allowing them to be called e.g. 

```
namespace my_namespace {
    macro PI { 3.14159265358979323846 }
}

....
fn main(): i32 {
    using std::io;
    printf("%f\n", my_namespace::PI!);
    <- 0;
}
```

**Comment by Spydr06** [comment]
like in C, macros are resolved before any "real" parsing is done, so the preprocessor is unaware of scopes/namespaces/etc.

**Comment by Its-Kenta** [comment]
Would there be plans to consider making macros be more aware of scopes/namespaces or strictly sticking to C style of macros?

**Comment by Spydr06** [comment]
No, I have no plans changing that I'm afraid. I chose this way of handling them as it is _suuuuper_ easy to implement.
