### ISSUE TITLE
VSC Extension as VSIX

### ISSUE THREAD

**Issue by Its-Kenta** [Spydr06/CSpydr#9]
Is it possible to package the VSC editor as VSIX please for ease of installation?
I've just tested it and it packaged ok, but does mention that LICENSE.txt is missing.

I've also pushed PR to slightly fix the installation for current version.

Thanks!

**Comment by Spydr06** [comment]
I've created a release for it: https://github.com/Spydr06/CSpydr/releases/tag/cspydr-vscode-extension-v0.1
